### PR TITLE
[WIP] Add missing options

### LINKED ISSUE #1: Access to javascript API
From what I understand, at the moment `gulp-duo` only accepts the `plugins` key as options. Now I'd like to set duo's `installTo` option, so that components aren't installed to `./src/components`, but to `./components`. And I'm sure that there are other situations in which you'd like to directly pass options to the javascript API.

Is there a way to do that with gulp-duo? I understand that it's still on the todo list: https://github.com/sergeyt/gulp-duo/blob/master/index.js#L65? Is it just a matter of accepting an options hash, or are there other things that need to be solved first?

### PR DESCRIPTION
**Pull request by ghost**
Thought I'd begin working on adding the missing options. Let me know what you think (it's still a work in progress, by the way).
- One important change is that I'm running duo from the root of the project (`process.cwd()`), which means that `components` won't be installed all over the place, but in `./components`. See: https://github.com/duojs/duo/issues/357. Otherwise, building `src/css/index.css` would create a `src/components` folder, which is wrong.
- Another thing that I added is the `buildTo` option. Problem is that asset paths aren't yet updated correctly in the css/js, and that folder structure is completely retained (which I assume you wouldn't want). Say you have `src/images/` and are building to `dist`. Duo will now create `assets/src/images`, when I'd want `dist/assets/images`. Any suggestions are welcome.

Fixes #1

### CODE REVIEW

**Comment by sergeyt** [comment]
@ismay thanks for PR! I thought this module is not used :)

**Comment by sergeyt** [comment]
@ismay let me know when publish new version on npm

**Comment by ghost** [comment]
> I thought this module is not used :)

Well I'd really like to use this, duo is an awesome build tool! But I think you misunderstood. The PR wasn't ready yet.

Some options aren't yet completely functional (like `buildTo`), or are still missing (like `includes`, `path`, `installPath`, `buildPath`). Could you please undo the merge, and wait until the PR is done? I'll change the title's [WIP] to [Ready] when it's ready. 

Thanks!

**Comment by sergeyt** [comment]
@ismay merge is reverted

**Comment by ghost** [comment]
Thanks! So would you have any suggestions for implementing the `buildTo` option? I'm not sure why it isn't updating the asset paths for example.

**Pull request merged**
